name: CI Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.12.0"
          cache: npm
      - run: npm ci
      - run: npm run -w express-backend lint
      - run: npm run -w react-frontend lint
      - run: npm run -w express-backend test
      - run: npm run -w react-frontend build
